// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h5baUxbXMoXXQDdi1jqzqA
// Component: TuJjF5DjUCD
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: U_rK3aBxPKvr/component

import { useScreenVariants as useScreenVariantsuhOqM2B1R2Y } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: -UhOqM2b1r2y/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_online_course_or_book.module.css"; // plasmic-import: h5baUxbXMoXXQDdi1jqzqA/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: TuJjF5DjUCD/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: qY-Kt0CLgsxU/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: Of5ZwnIwMUdO/icon
import _227601RightArrowIconsvgIcon from "./icons/PlasmicIcon___227601RightArrowIconsvg"; // plasmic-import: 0LQGQmgOGfcF/icon
import image8L6TBnkWx6Ypb from "./images/image8.png"; // plasmic-import: l6TBnkWx6YPB/picture
import image2JG9MQp2DXfXe from "./images/image2.png"; // plasmic-import: jG9mQP2DXfXe/picture
import group3UBrZajZWgO from "./images/group3.svg"; // plasmic-import: uBRZajZ_wgO-/picture
import group6FiQ7IXb8NgRs from "./images/group6.svg"; // plasmic-import: FiQ7iXb8NgRS/picture
import groupUmOYwnOG8N from "./images/group.svg"; // plasmic-import: umOYwn-oG8-n/picture
import group5LmWgMDm4Wv7 from "./images/group5.svg"; // plasmic-import: _LmWgMDm4Wv7/picture
import group7C8SBb8Wmyi2X from "./images/group7.svg"; // plasmic-import: C8sBb8wmyi2X/picture
import group2OmUl9U9Mo3Bx from "./images/group2.svg"; // plasmic-import: omUL9u9mo3BX/picture
import group48H8D9C7Vw6 from "./images/group4.svg"; // plasmic-import: 8h-8D_9C7VW6/picture
import imageXh3Yqa5Un2Cn from "./images/image.png"; // plasmic-import: xh3Yqa5Un2CN/picture
import image7DOGkC1UXxqoH from "./images/image7.png"; // plasmic-import: dOGkC1UXxqoH/picture
import image49GuharkCkKFk from "./images/image4.png"; // plasmic-import: 9GuharkCkKFk/picture
import image9DtjIFcNjnPxP from "./images/image9.png"; // plasmic-import: DtjIFcNJNPxP/picture
import icons8TwittersvgNcicCOyNzi7C from "./images/icons8Twittersvg.svg"; // plasmic-import: NcicCOyNzi7c/picture
import icons8FacebooksvgEe0SskHzG8 from "./images/icons8Facebooksvg.svg"; // plasmic-import: ee0SSK--HzG8/picture
import icons8YoutubesvgWytlEt0GZgpn from "./images/icons8Youtubesvg.svg"; // plasmic-import: wytlET0gZgpn/picture
import icons8VimeosvgZAlFr0LVhY from "./images/icons8Vimeosvg.svg"; // plasmic-import: _Z-AlFr0lVhY/picture

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<"header">;
  logoWrap?: p.Flex<"div">;
  logo?: p.Flex<typeof p.PlasmicImg>;
  navmenu?: p.Flex<"div">;
  link3?: p.Flex<"a">;
  link2?: p.Flex<"a">;
  navBarButtonBlock?: p.Flex<"div">;
  btnText?: p.Flex<"div">;
  section1?: p.Flex<"section">;
  container?: p.Flex<"div">;
  flexBox?: p.Flex<"div">;
  bannerImage?: p.Flex<"div">;
  contentBlock?: p.Flex<"div">;
  mainHeading?: p.Flex<"h1">;
  peraBanner?: p.Flex<"p">;
  section2?: p.Flex<"section">;
  subHeading?: p.Flex<"h2">;
  logoContainer?: p.Flex<"div">;
  section3?: p.Flex<"section">;
  twoSideBox?: p.Flex<"div">;
  subHeading2?: p.Flex<"h2">;
  peraContent?: p.Flex<"p">;
  unorderList?: p.Flex<"ul">;
  listIteam?: p.Flex<"li">;
  listIteam3?: p.Flex<"li">;
  listIteam4?: p.Flex<"li">;
  listIteam5?: p.Flex<"li">;
  listIteam6?: p.Flex<"li">;
  listIteam7?: p.Flex<"li">;
  listIteam8?: p.Flex<"li">;
  bannerImage2?: p.Flex<"div">;
  imageMarketing2?: p.Flex<typeof p.PlasmicImg>;
  section4?: p.Flex<"section">;
  testimonialText?: p.Flex<"h2">;
  position?: p.Flex<"p">;
  section5?: p.Flex<"section">;
  twoSidedContent?: p.Flex<"div">;
  subHeading3?: p.Flex<"h2">;
  line2?: p.Flex<"div">;
  section6?: p.Flex<"section">;
  twoSideBox2?: p.Flex<"div">;
  subHeading4?: p.Flex<"h2">;
  peraContent2?: p.Flex<"p">;
  unorderList2?: p.Flex<"ul">;
  listIteam2?: p.Flex<"li">;
  listIteam9?: p.Flex<"li">;
  listIteam10?: p.Flex<"li">;
  listIteam11?: p.Flex<"li">;
  listIteam12?: p.Flex<"li">;
  listIteam13?: p.Flex<"li">;
  bannerImage3?: p.Flex<"div">;
  imageMarketing3?: p.Flex<typeof p.PlasmicImg>;
  section7?: p.Flex<"section">;
  subHeading5?: p.Flex<"h2">;
  line3?: p.Flex<"div">;
  blockChapterContent?: p.Flex<"div">;
  blockChapterContent4?: p.Flex<"div">;
  blockChapterContent2?: p.Flex<"div">;
  blockChapterContent3?: p.Flex<"div">;
  section8?: p.Flex<"section">;
  avtarContent?: p.Flex<"div">;
  avatarImage?: p.Flex<"div">;
  section9?: p.Flex<"section">;
  svg?: p.Flex<"svg">;
  footer?: p.Flex<"footer">;
  footerLogo?: p.Flex<"div">;
  logo2?: p.Flex<typeof p.PlasmicImg>;
  footerLink?: p.Flex<"a">;
  footerLink2?: p.Flex<"a">;
  footerLink4?: p.Flex<"a">;
  footerLink5?: p.Flex<"a">;
  copyRight?: p.Flex<"p">;
  socialIcons?: p.Flex<"div">;
  twitter?: p.Flex<typeof p.PlasmicImg>;
  facebook?: p.Flex<typeof p.PlasmicImg>;
  youtube?: p.Flex<typeof p.PlasmicImg>;
  vimeo?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsuhOqM2B1R2Y()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <header
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames(projectcss.all, sty.navBar)}
          >
            <div
              data-plasmic-name={"logoWrap"}
              data-plasmic-override={overrides.logoWrap}
              className={classNames(projectcss.all, sty.logoWrap)}
            >
              <p.PlasmicImg
                data-plasmic-name={"logo"}
                data-plasmic-override={overrides.logo}
                alt={""}
                className={classNames(sty.logo)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"220px" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: image8L6TBnkWx6Ypb,
                  fullWidth: 186,
                  fullHeight: 80,
                  aspectRatio: undefined
                }}
              />
            </div>

            {true ? (
              <div
                data-plasmic-name={"navmenu"}
                data-plasmic-override={overrides.navmenu}
                className={classNames(projectcss.all, sty.navmenu)}
              >
                <a
                  data-plasmic-name={"link3"}
                  data-plasmic-override={overrides.link3}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link3
                  )}
                  href={"/" as const}
                >
                  {"Pricing"}
                </a>

                <a
                  data-plasmic-name={"link2"}
                  data-plasmic-override={overrides.link2}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link2
                  )}
                  href={"#" as const}
                >
                  {"Story"}
                </a>
              </div>
            ) : null}

            <div
              data-plasmic-name={"navBarButtonBlock"}
              data-plasmic-override={overrides.navBarButtonBlock}
              className={classNames(projectcss.all, sty.navBarButtonBlock)}
            >
              <Button
                className={classNames("__wab_instance", sty.button___3H1Rx)}
                color={"red" as const}
                shape={"rounded" as const}
              >
                <div
                  data-plasmic-name={"btnText"}
                  data-plasmic-override={overrides.btnText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.btnText
                  )}
                >
                  {"Start Learning"}
                </div>
              </Button>
            </div>
          </header>

          <section
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            className={classNames(projectcss.all, sty.section1)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"flexBox"}
                data-plasmic-override={overrides.flexBox}
                hasGap={true}
                className={classNames(projectcss.all, sty.flexBox)}
              >
                <div className={classNames(projectcss.all, sty.column___0CneK)}>
                  <div
                    data-plasmic-name={"bannerImage"}
                    data-plasmic-override={overrides.bannerImage}
                    className={classNames(projectcss.all, sty.bannerImage)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__reqCh)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: image2JG9MQp2DXfXe,
                        fullWidth: 1332,
                        fullHeight: 2080,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__tqcJw)}>
                  <div
                    data-plasmic-name={"contentBlock"}
                    data-plasmic-override={overrides.contentBlock}
                    className={classNames(projectcss.all, sty.contentBlock)}
                  >
                    <h1
                      data-plasmic-name={"mainHeading"}
                      data-plasmic-override={overrides.mainHeading}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.mainHeading
                      )}
                    >
                      {"The Ultimate Guide to High-Performance Landing Pages"}
                    </h1>

                    <p
                      data-plasmic-name={"peraBanner"}
                      data-plasmic-override={overrides.peraBanner}
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        sty.peraBanner
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pri6W
                        )}
                      >
                        {
                          "Your go-to guide for both B2B and B2C digital marketing pages.\n\nWe will share with you the hard-won tips and tricks we've gained from developing over 75 high-converting landing pages clients across multiple industries. Everything from ad image and copy, to page design and conversion strategies are shared here in broad strokes for you to take home and deploy."
                        }
                      </div>
                    </p>

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0B9QB
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__es8Wf
                          )}
                          color={"red" as const}
                          shape={"rounded" as const}
                          showEndIcon={true}
                        >
                          {"Access the course"}
                        </Button>
                      </div>
                    ) : null}
                  </div>
                </div>
              </p.Stack>
            </div>
          </section>

          <p.Stack
            as={"section"}
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            hasGap={true}
            className={classNames(projectcss.all, sty.section2)}
          >
            <h2
              data-plasmic-name={"subHeading"}
              data-plasmic-override={overrides.subHeading}
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.subHeading
              )}
            >
              {"Used by marketers at:"}
            </h2>

            <p.Stack
              as={"div"}
              data-plasmic-name={"logoContainer"}
              data-plasmic-override={overrides.logoContainer}
              hasGap={true}
              className={classNames(projectcss.all, sty.logoContainer)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___98WAr)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("77px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("100px" as const)
                    : ("180px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: group3UBrZajZWgO,
                  fullWidth: 180,
                  fullHeight: 77,
                  aspectRatio: 2.337662
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__a6NYo)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("85px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("100px" as const)
                    : ("180px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: group6FiQ7IXb8NgRs,
                  fullWidth: 180,
                  fullHeight: 85,
                  aspectRatio: 2.117647
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__tz6S)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("66px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("120px" as const)
                    : ("157px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: groupUmOYwnOG8N,
                  fullWidth: 157,
                  fullHeight: 66,
                  aspectRatio: 2.378788
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__agog3)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("80.999px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("100px" as const)
                    : ("164.999px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: group5LmWgMDm4Wv7,
                  fullWidth: 164.999,
                  fullHeight: 80.999,
                  aspectRatio: 2.037037
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__tsb2N)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("auto" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("100px" as const)
                    : ("143px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: group7C8SBb8Wmyi2X,
                  fullWidth: 143,
                  fullHeight: 91,
                  aspectRatio: 1.571429
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__dEaPa)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("76.999px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("138px" as const)
                    : ("168.999px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: group2OmUl9U9Mo3Bx,
                  fullWidth: 168.999,
                  fullHeight: 76.999,
                  aspectRatio: 2.194805
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__dU2P6)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("auto" as const)
                    : ("87px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("100px" as const)
                    : ("152.999px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: group48H8D9C7Vw6,
                  fullWidth: 152.999,
                  fullHeight: 87,
                  aspectRatio: 1.758621
                }}
              />
            </p.Stack>
          </p.Stack>

          <section
            data-plasmic-name={"section3"}
            data-plasmic-override={overrides.section3}
            className={classNames(projectcss.all, sty.section3)}
          >
            <div
              data-plasmic-name={"twoSideBox"}
              data-plasmic-override={overrides.twoSideBox}
              className={classNames(projectcss.all, sty.twoSideBox)}
            >
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox__kzn0)}>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__baNiZ)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__khoNk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__eDbpA
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bNbW6
                            )}
                          >
                            <h2
                              data-plasmic-name={"subHeading2"}
                              data-plasmic-override={overrides.subHeading2}
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                sty.subHeading2
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ctaab
                                )}
                              >
                                {"What you'll learn"}
                              </div>

                              <p
                                data-plasmic-name={"peraContent"}
                                data-plasmic-override={overrides.peraContent}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.p,
                                  projectcss.__wab_text,
                                  sty.peraContent
                                )}
                              >
                                {
                                  "How this course will take you from zero to hero:"
                                }
                              </p>

                              <ul
                                data-plasmic-name={"unorderList"}
                                data-plasmic-override={overrides.unorderList}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.unorderList
                                )}
                              >
                                <li
                                  data-plasmic-name={"listIteam"}
                                  data-plasmic-override={overrides.listIteam}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.listIteam
                                  )}
                                >
                                  {
                                    "Describe some topic covered in this info product."
                                  }
                                </li>

                                <li
                                  data-plasmic-name={"listIteam3"}
                                  data-plasmic-override={overrides.listIteam3}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.listIteam3
                                  )}
                                >
                                  {
                                    "Describe some topic covered in this info product."
                                  }
                                </li>

                                <li
                                  data-plasmic-name={"listIteam4"}
                                  data-plasmic-override={overrides.listIteam4}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.listIteam4
                                  )}
                                >
                                  {
                                    "Describe some topic covered in this info product."
                                  }
                                </li>

                                <li
                                  data-plasmic-name={"listIteam5"}
                                  data-plasmic-override={overrides.listIteam5}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.listIteam5
                                  )}
                                >
                                  {
                                    "Describe some topic covered in this info product."
                                  }
                                </li>

                                <li
                                  data-plasmic-name={"listIteam6"}
                                  data-plasmic-override={overrides.listIteam6}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.listIteam6
                                  )}
                                >
                                  {
                                    "Describe some topic covered in this info product."
                                  }
                                </li>

                                <li
                                  data-plasmic-name={"listIteam7"}
                                  data-plasmic-override={overrides.listIteam7}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.listIteam7
                                  )}
                                >
                                  {
                                    "Describe some topic covered in this info product."
                                  }
                                </li>

                                <li
                                  data-plasmic-name={"listIteam8"}
                                  data-plasmic-override={overrides.listIteam8}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    projectcss.__wab_text,
                                    sty.listIteam8
                                  )}
                                >
                                  {
                                    "Describe some topic covered in this info product."
                                  }
                                </li>
                              </ul>
                            </h2>
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__q9Izq
                            )}
                            color={"red" as const}
                            shape={"rounded" as const}
                            showEndIcon={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zXdKk
                              )}
                            >
                              {"Start learning"}
                            </div>
                          </Button>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__l0HQi
                          )}
                        >
                          <div
                            data-plasmic-name={"bannerImage2"}
                            data-plasmic-override={overrides.bannerImage2}
                            className={classNames(
                              projectcss.all,
                              sty.bannerImage2
                            )}
                          >
                            <p.PlasmicImg
                              data-plasmic-name={"imageMarketing2"}
                              data-plasmic-override={overrides.imageMarketing2}
                              alt={""}
                              className={classNames(sty.imageMarketing2)}
                              displayHeight={
                                hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? ("auto" as const)
                                  : ("100%" as const)
                              }
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={
                                hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? ("400px" as const)
                                  : ("100%" as const)
                              }
                              loading={"lazy" as const}
                              src={{
                                src: imageXh3Yqa5Un2Cn,
                                fullWidth: 1600,
                                fullHeight: 1200,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  ) : null}
                </div>
              ) : null}
            </div>
          </section>

          <section
            data-plasmic-name={"section4"}
            data-plasmic-override={overrides.section4}
            className={classNames(projectcss.all, sty.section4)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__fxSpQ)}>
              <div className={classNames(projectcss.all, sty.columns__pDwPh)}>
                <div className={classNames(projectcss.all, sty.column__xaozz)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__xdDPm)}
                    displayHeight={"256px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"256px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: image7DOGkC1UXxqoH,
                      fullWidth: 1112,
                      fullHeight: 794,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__pFeIf)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gw6K)}
                  >
                    <h2
                      data-plasmic-name={"testimonialText"}
                      data-plasmic-override={overrides.testimonialText}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.testimonialText
                      )}
                    >
                      {
                        "“This course is a must-take for anyone in digital marketing. Worth every penny.”"
                      }
                    </h2>

                    <p
                      data-plasmic-name={"position"}
                      data-plasmic-override={overrides.position}
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.__wab_text,
                        sty.position
                      )}
                    >
                      {"Jane Doe, Sr. Marketing Manager at Company"}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section
            data-plasmic-name={"section5"}
            data-plasmic-override={overrides.section5}
            className={classNames(projectcss.all, sty.section5)}
          >
            <div
              data-plasmic-name={"twoSidedContent"}
              data-plasmic-override={overrides.twoSidedContent}
              className={classNames(projectcss.all, sty.twoSidedContent)}
            >
              <h2
                data-plasmic-name={"subHeading3"}
                data-plasmic-override={overrides.subHeading3}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.subHeading3
                )}
              >
                {"Curriculum Overview"}
              </h2>

              <div
                data-plasmic-name={"line2"}
                data-plasmic-override={overrides.line2}
                className={classNames(projectcss.all, sty.line2)}
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__hCtgc)}
              >
                <div className={classNames(projectcss.all, sty.column__joY8)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___16BnZ
                    )}
                  >
                    {"Chapter Title"}
                  </h2>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__mEtNd
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>

                <div className={classNames(projectcss.all, sty.column__hjsMf)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__v1Lk
                    )}
                  >
                    {"Chapter Title"}
                  </h2>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__trUDx
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>

                <div className={classNames(projectcss.all, sty.column__pL5Cb)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ayVpE
                    )}
                  >
                    {"Chapter Title"}
                  </h2>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__xsBTr
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>

                <div className={classNames(projectcss.all, sty.column__fCAwh)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__wbG6J
                    )}
                  >
                    {"Chapter Title"}
                  </h2>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p___2YQcg
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>

                <div className={classNames(projectcss.all, sty.column__rsSax)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__nHixT
                    )}
                  >
                    {"Chapter Title"}
                  </h2>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__wkEs4
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>

                <div className={classNames(projectcss.all, sty.column__jXk7L)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__lZruC
                    )}
                  >
                    {"Chapter Title"}
                  </h2>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__qCh3Y
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
              </p.Stack>
            </div>
          </section>

          <section
            data-plasmic-name={"section6"}
            data-plasmic-override={overrides.section6}
            className={classNames(projectcss.all, sty.section6)}
          >
            <div
              data-plasmic-name={"twoSideBox2"}
              data-plasmic-override={overrides.twoSideBox2}
              className={classNames(projectcss.all, sty.twoSideBox2)}
            >
              <div className={classNames(projectcss.all, sty.columns__cNcea)}>
                <div className={classNames(projectcss.all, sty.column__s114C)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__imjwr)}
                  >
                    <h2
                      data-plasmic-name={"subHeading4"}
                      data-plasmic-override={overrides.subHeading4}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        sty.subHeading4
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kqo4G
                        )}
                      >
                        {"Practical exercises"}
                      </div>

                      <p
                        data-plasmic-name={"peraContent2"}
                        data-plasmic-override={overrides.peraContent2}
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.peraContent2
                        )}
                      >
                        {"How you'll implement what you learn"}
                      </p>

                      <ul
                        data-plasmic-name={"unorderList2"}
                        data-plasmic-override={overrides.unorderList2}
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.unorderList2
                        )}
                      >
                        <li
                          data-plasmic-name={"listIteam2"}
                          data-plasmic-override={overrides.listIteam2}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam2
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>

                        <li
                          data-plasmic-name={"listIteam9"}
                          data-plasmic-override={overrides.listIteam9}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam9
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>

                        <li
                          data-plasmic-name={"listIteam10"}
                          data-plasmic-override={overrides.listIteam10}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam10
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>

                        <li
                          data-plasmic-name={"listIteam11"}
                          data-plasmic-override={overrides.listIteam11}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam11
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>

                        <li
                          data-plasmic-name={"listIteam12"}
                          data-plasmic-override={overrides.listIteam12}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam12
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>

                        <li
                          data-plasmic-name={"listIteam13"}
                          data-plasmic-override={overrides.listIteam13}
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.listIteam13
                          )}
                        >
                          {"Describe a practice exercise."}
                        </li>
                      </ul>
                    </h2>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__fcEE)}
                    color={"red" as const}
                    shape={"rounded" as const}
                    showEndIcon={true}
                  >
                    {"Start learning"}
                  </Button>
                </div>

                <div className={classNames(projectcss.all, sty.column__akzP0)}>
                  <div
                    data-plasmic-name={"bannerImage3"}
                    data-plasmic-override={overrides.bannerImage3}
                    className={classNames(projectcss.all, sty.bannerImage3)}
                  >
                    <p.PlasmicImg
                      data-plasmic-name={"imageMarketing3"}
                      data-plasmic-override={overrides.imageMarketing3}
                      alt={""}
                      className={classNames(sty.imageMarketing3)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("auto" as const)
                          : ("100%" as const)
                      }
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? ("400px" as const)
                          : ("100%" as const)
                      }
                      loading={"lazy" as const}
                      src={{
                        src: imageXh3Yqa5Un2Cn,
                        fullWidth: 1600,
                        fullHeight: 1200,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section
            data-plasmic-name={"section7"}
            data-plasmic-override={overrides.section7}
            className={classNames(projectcss.all, sty.section7)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__zeWi5)}>
              <h2
                data-plasmic-name={"subHeading5"}
                data-plasmic-override={overrides.subHeading5}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.subHeading5
                )}
              >
                {"Who should take this course?"}
              </h2>

              <div
                data-plasmic-name={"line3"}
                data-plasmic-override={overrides.line3}
                className={classNames(projectcss.all, sty.line3)}
              />
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xzREv)}
            >
              <div className={classNames(projectcss.all, sty.column__oLfXe)}>
                <div
                  data-plasmic-name={"blockChapterContent"}
                  data-plasmic-override={overrides.blockChapterContent}
                  className={classNames(
                    projectcss.all,
                    sty.blockChapterContent
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fnLbH
                    )}
                  >
                    {"Marketers"}
                  </div>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__cs2Bs
                    )}
                  >
                    {"Learn how all of the marketing pieces fit together"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__kzh1C
                    )}
                  >
                    {"Master digital marketing for any business"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li___0QhM4
                    )}
                  >
                    {"Get access to marketing gurus and their tips"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__sprrl
                    )}
                  >
                    {"Prepare killer presentations and collateral"}
                  </li>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__qZ4G)}>
                <div
                  data-plasmic-name={"blockChapterContent4"}
                  data-plasmic-override={overrides.blockChapterContent4}
                  className={classNames(
                    projectcss.all,
                    sty.blockChapterContent4
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2KSfq
                    )}
                  >
                    {"Product managers"}
                  </div>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__ob6Tg
                    )}
                  >
                    {"Understand the context of your product work"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__fsAKe
                    )}
                  >
                    {"Learn how to segment your audience properly"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li___36Zt9
                    )}
                  >
                    {"Implement brand voice and style in your work"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__ldJEu
                    )}
                  >
                    {"Connect top of funnel activities with your flow"}
                  </li>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__sUjB)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dds7F
                  )}
                >
                  {"Designers"}
                </div>

                <li
                  className={classNames(
                    projectcss.all,
                    projectcss.li,
                    sty.li__i6H4X
                  )}
                >
                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li___9Cxfj
                    )}
                  >
                    {"Learn how your design can inspire action"}
                  </li>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vcXhk
                    )}
                  >
                    {"Gain big picture insights that affect design"}
                  </div>

                  <div
                    data-plasmic-name={"blockChapterContent2"}
                    data-plasmic-override={overrides.blockChapterContent2}
                    className={classNames(
                      projectcss.all,
                      sty.blockChapterContent2
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__ce1DY
                      )}
                    >
                      {"Make advertisements that convert"}
                    </li>

                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li___7OXra
                      )}
                    >
                      {"Create digital assets for the right audience"}
                    </li>
                  </div>
                </li>
              </div>

              <div className={classNames(projectcss.all, sty.column__e34Ra)}>
                <div
                  data-plasmic-name={"blockChapterContent3"}
                  data-plasmic-override={overrides.blockChapterContent3}
                  className={classNames(
                    projectcss.all,
                    sty.blockChapterContent3
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vPcO7
                    )}
                  >
                    {"Business owners"}
                  </div>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__uJ4Rd
                    )}
                  >
                    {"Kickstart your marketing plan and efforts"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__g86Jn
                    )}
                  >
                    {"Upgrade your brand, website and social media"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__eWnSu
                    )}
                  >
                    {"Prepare effective collateral for your business"}
                  </li>

                  <li
                    className={classNames(
                      projectcss.all,
                      projectcss.li,
                      projectcss.__wab_text,
                      sty.li__va0WW
                    )}
                  >
                    {"Start advertising your company online"}
                  </li>
                </div>
              </div>
            </p.Stack>
          </section>

          <section
            data-plasmic-name={"section8"}
            data-plasmic-override={overrides.section8}
            className={classNames(projectcss.all, sty.section8)}
          >
            <div className={classNames(projectcss.all, sty.columns__xsknk)}>
              <div className={classNames(projectcss.all, sty.column__znm6W)}>
                <div
                  data-plasmic-name={"avtarContent"}
                  data-plasmic-override={overrides.avtarContent}
                  className={classNames(projectcss.all, sty.avtarContent)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ajPqn
                    )}
                  >
                    {"About the instructor"}
                  </h2>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p___7PSjw
                    )}
                  >
                    {"Jane Doe, Title"}
                  </p>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__u4Ud
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__v9A2E
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>

                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p___8A2Nn
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                    }
                  </p>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__ozcJm)}>
                <div
                  data-plasmic-name={"avatarImage"}
                  data-plasmic-override={overrides.avatarImage}
                  className={classNames(projectcss.all, sty.avatarImage)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bi7K1)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("100%" as const)
                        : ("auto" as const)
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? ("400px" as const)
                        : ("auto" as const)
                    }
                    loading={"lazy" as const}
                    src={{
                      src: image49GuharkCkKFk,
                      fullWidth: 930,
                      fullHeight: 1162,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </section>

          <section
            data-plasmic-name={"section9"}
            data-plasmic-override={overrides.section9}
            className={classNames(projectcss.all, sty.section9)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__xUbXj)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__eXikb
                )}
              >
                {"Access the course today"}
              </h2>
            </div>

            <Button
              className={classNames("__wab_instance", sty.button__ztJKx)}
              color={"white" as const}
              endIcon={
                <_227601RightArrowIconsvgIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />
              }
              shape={"rounded" as const}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cFz2K
                )}
              >
                {"Access the course"}
              </div>
            </Button>
          </section>

          <footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.columns__b7JBk)}>
              <div className={classNames(projectcss.all, sty.column__nbKbT)}>
                <div
                  data-plasmic-name={"footerLogo"}
                  data-plasmic-override={overrides.footerLogo}
                  className={classNames(projectcss.all, sty.footerLogo)}
                >
                  <p.PlasmicImg
                    data-plasmic-name={"logo2"}
                    data-plasmic-override={overrides.logo2}
                    alt={""}
                    className={classNames(sty.logo2)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"300px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: image9DtjIFcNjnPxP,
                      fullWidth: 374,
                      fullHeight: 156,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.column__dltcC)}>
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__by2Ws
                  )}
                >
                  {"Company"}
                </h3>

                <a
                  data-plasmic-name={"footerLink"}
                  data-plasmic-override={overrides.footerLink}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink
                  )}
                  href={"/" as const}
                >
                  {"Story"}
                </a>

                <a
                  data-plasmic-name={"footerLink2"}
                  data-plasmic-override={overrides.footerLink2}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink2
                  )}
                  href={"/" as const}
                >
                  {"Pricing"}
                </a>
              </div>

              <div className={classNames(projectcss.all, sty.column__acl7)}>
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__xrAy
                  )}
                >
                  {"Legal"}
                </h3>

                <a
                  data-plasmic-name={"footerLink4"}
                  data-plasmic-override={overrides.footerLink4}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink4
                  )}
                  href={"/" as const}
                >
                  {"Terms & Conditions"}
                </a>

                <a
                  data-plasmic-name={"footerLink5"}
                  data-plasmic-override={overrides.footerLink5}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.footerLink5
                  )}
                  href={"/" as const}
                >
                  {"Privacy Policy"}
                </a>
              </div>
            </div>
          </footer>

          <div className={classNames(projectcss.all, sty.freeBox__uF6Z3)}>
            <div className={classNames(projectcss.all, sty.columns__eB0WD)}>
              <div className={classNames(projectcss.all, sty.column__pIQm5)}>
                <p
                  data-plasmic-name={"copyRight"}
                  data-plasmic-override={overrides.copyRight}
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.__wab_text,
                    sty.copyRight
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "© Company. All rights reserved. This site proudly built with "
                      }
                    </React.Fragment>
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link__ypYdO
                      )}
                      href={"https://www.plasmic.app" as const}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Plasmic"
                        : "Plasmic"}
                    </a>
                    <React.Fragment>{"."}</React.Fragment>
                  </React.Fragment>
                </p>
              </div>

              <div className={classNames(projectcss.all, sty.column___67Zi)}>
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"socialIcons"}
                  data-plasmic-override={overrides.socialIcons}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.socialIcons)}
                >
                  {true ? (
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__hFSg9
                      )}
                      href={"https://twitter.com/" as const}
                      target={"_blank" as const}
                    >
                      <p.PlasmicImg
                        data-plasmic-name={"twitter"}
                        data-plasmic-override={overrides.twitter}
                        alt={""}
                        className={classNames(sty.twitter)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"30px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: icons8TwittersvgNcicCOyNzi7C,
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />
                    </a>
                  ) : null}
                  {true ? (
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___5TuXe
                      )}
                      href={"#" as const}
                      target={"_blank" as const}
                    >
                      <p.PlasmicImg
                        data-plasmic-name={"facebook"}
                        data-plasmic-override={overrides.facebook}
                        alt={""}
                        className={classNames(sty.facebook)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"30px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: icons8FacebooksvgEe0SskHzG8,
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />
                    </a>
                  ) : null}
                  {true ? (
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__xkiQ
                      )}
                      href={"#" as const}
                      target={"_blank" as const}
                    >
                      <p.PlasmicImg
                        data-plasmic-name={"youtube"}
                        data-plasmic-override={overrides.youtube}
                        alt={""}
                        className={classNames(sty.youtube)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"30px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: icons8YoutubesvgWytlEt0GZgpn,
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />
                    </a>
                  ) : null}
                  {true ? (
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__xeemS
                      )}
                      href={"#" as const}
                    >
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__p4WKe
                          )}
                        >
                          <p.PlasmicImg
                            data-plasmic-name={"vimeo"}
                            data-plasmic-override={overrides.vimeo}
                            alt={""}
                            className={classNames(sty.vimeo)}
                            displayHeight={"auto" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"30px" as const}
                            loading={"lazy" as const}
                            src={{
                              src: icons8VimeosvgZAlFr0LVhY,
                              fullWidth: 150,
                              fullHeight: 150,
                              aspectRatio: 1
                            }}
                          />
                        </div>
                      ) : null}
                    </a>
                  ) : null}
                </p.Stack>
              </div>
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "logoWrap",
    "logo",
    "navmenu",
    "link3",
    "link2",
    "navBarButtonBlock",
    "btnText",
    "section1",
    "container",
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner",
    "section2",
    "subHeading",
    "logoContainer",
    "section3",
    "twoSideBox",
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8",
    "bannerImage2",
    "imageMarketing2",
    "section4",
    "testimonialText",
    "position",
    "section5",
    "twoSidedContent",
    "subHeading3",
    "line2",
    "section6",
    "twoSideBox2",
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13",
    "bannerImage3",
    "imageMarketing3",
    "section7",
    "subHeading5",
    "line3",
    "blockChapterContent",
    "blockChapterContent4",
    "blockChapterContent2",
    "blockChapterContent3",
    "section8",
    "avtarContent",
    "avatarImage",
    "section9",
    "svg",
    "footer",
    "footerLogo",
    "logo2",
    "footerLink",
    "footerLink2",
    "footerLink4",
    "footerLink5",
    "copyRight",
    "socialIcons",
    "twitter",
    "facebook",
    "youtube",
    "vimeo"
  ],
  navBar: [
    "navBar",
    "logoWrap",
    "logo",
    "navmenu",
    "link3",
    "link2",
    "navBarButtonBlock",
    "btnText"
  ],
  logoWrap: ["logoWrap", "logo"],
  logo: ["logo"],
  navmenu: ["navmenu", "link3", "link2"],
  link3: ["link3"],
  link2: ["link2"],
  navBarButtonBlock: ["navBarButtonBlock", "btnText"],
  btnText: ["btnText"],
  section1: [
    "section1",
    "container",
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner"
  ],
  container: [
    "container",
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner"
  ],
  flexBox: [
    "flexBox",
    "bannerImage",
    "contentBlock",
    "mainHeading",
    "peraBanner"
  ],
  bannerImage: ["bannerImage"],
  contentBlock: ["contentBlock", "mainHeading", "peraBanner"],
  mainHeading: ["mainHeading"],
  peraBanner: ["peraBanner"],
  section2: ["section2", "subHeading", "logoContainer"],
  subHeading: ["subHeading"],
  logoContainer: ["logoContainer"],
  section3: [
    "section3",
    "twoSideBox",
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8",
    "bannerImage2",
    "imageMarketing2"
  ],
  twoSideBox: [
    "twoSideBox",
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8",
    "bannerImage2",
    "imageMarketing2"
  ],
  subHeading2: [
    "subHeading2",
    "peraContent",
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8"
  ],
  peraContent: ["peraContent"],
  unorderList: [
    "unorderList",
    "listIteam",
    "listIteam3",
    "listIteam4",
    "listIteam5",
    "listIteam6",
    "listIteam7",
    "listIteam8"
  ],
  listIteam: ["listIteam"],
  listIteam3: ["listIteam3"],
  listIteam4: ["listIteam4"],
  listIteam5: ["listIteam5"],
  listIteam6: ["listIteam6"],
  listIteam7: ["listIteam7"],
  listIteam8: ["listIteam8"],
  bannerImage2: ["bannerImage2", "imageMarketing2"],
  imageMarketing2: ["imageMarketing2"],
  section4: ["section4", "testimonialText", "position"],
  testimonialText: ["testimonialText"],
  position: ["position"],
  section5: ["section5", "twoSidedContent", "subHeading3", "line2"],
  twoSidedContent: ["twoSidedContent", "subHeading3", "line2"],
  subHeading3: ["subHeading3"],
  line2: ["line2"],
  section6: [
    "section6",
    "twoSideBox2",
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13",
    "bannerImage3",
    "imageMarketing3"
  ],
  twoSideBox2: [
    "twoSideBox2",
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13",
    "bannerImage3",
    "imageMarketing3"
  ],
  subHeading4: [
    "subHeading4",
    "peraContent2",
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13"
  ],
  peraContent2: ["peraContent2"],
  unorderList2: [
    "unorderList2",
    "listIteam2",
    "listIteam9",
    "listIteam10",
    "listIteam11",
    "listIteam12",
    "listIteam13"
  ],
  listIteam2: ["listIteam2"],
  listIteam9: ["listIteam9"],
  listIteam10: ["listIteam10"],
  listIteam11: ["listIteam11"],
  listIteam12: ["listIteam12"],
  listIteam13: ["listIteam13"],
  bannerImage3: ["bannerImage3", "imageMarketing3"],
  imageMarketing3: ["imageMarketing3"],
  section7: [
    "section7",
    "subHeading5",
    "line3",
    "blockChapterContent",
    "blockChapterContent4",
    "blockChapterContent2",
    "blockChapterContent3"
  ],
  subHeading5: ["subHeading5"],
  line3: ["line3"],
  blockChapterContent: ["blockChapterContent"],
  blockChapterContent4: ["blockChapterContent4"],
  blockChapterContent2: ["blockChapterContent2"],
  blockChapterContent3: ["blockChapterContent3"],
  section8: ["section8", "avtarContent", "avatarImage"],
  avtarContent: ["avtarContent"],
  avatarImage: ["avatarImage"],
  section9: ["section9", "svg"],
  svg: ["svg"],
  footer: [
    "footer",
    "footerLogo",
    "logo2",
    "footerLink",
    "footerLink2",
    "footerLink4",
    "footerLink5"
  ],
  footerLogo: ["footerLogo", "logo2"],
  logo2: ["logo2"],
  footerLink: ["footerLink"],
  footerLink2: ["footerLink2"],
  footerLink4: ["footerLink4"],
  footerLink5: ["footerLink5"],
  copyRight: ["copyRight"],
  socialIcons: ["socialIcons", "twitter", "facebook", "youtube", "vimeo"],
  twitter: ["twitter"],
  facebook: ["facebook"],
  youtube: ["youtube"],
  vimeo: ["vimeo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: "header";
  logoWrap: "div";
  logo: typeof p.PlasmicImg;
  navmenu: "div";
  link3: "a";
  link2: "a";
  navBarButtonBlock: "div";
  btnText: "div";
  section1: "section";
  container: "div";
  flexBox: "div";
  bannerImage: "div";
  contentBlock: "div";
  mainHeading: "h1";
  peraBanner: "p";
  section2: "section";
  subHeading: "h2";
  logoContainer: "div";
  section3: "section";
  twoSideBox: "div";
  subHeading2: "h2";
  peraContent: "p";
  unorderList: "ul";
  listIteam: "li";
  listIteam3: "li";
  listIteam4: "li";
  listIteam5: "li";
  listIteam6: "li";
  listIteam7: "li";
  listIteam8: "li";
  bannerImage2: "div";
  imageMarketing2: typeof p.PlasmicImg;
  section4: "section";
  testimonialText: "h2";
  position: "p";
  section5: "section";
  twoSidedContent: "div";
  subHeading3: "h2";
  line2: "div";
  section6: "section";
  twoSideBox2: "div";
  subHeading4: "h2";
  peraContent2: "p";
  unorderList2: "ul";
  listIteam2: "li";
  listIteam9: "li";
  listIteam10: "li";
  listIteam11: "li";
  listIteam12: "li";
  listIteam13: "li";
  bannerImage3: "div";
  imageMarketing3: typeof p.PlasmicImg;
  section7: "section";
  subHeading5: "h2";
  line3: "div";
  blockChapterContent: "div";
  blockChapterContent4: "div";
  blockChapterContent2: "div";
  blockChapterContent3: "div";
  section8: "section";
  avtarContent: "div";
  avatarImage: "div";
  section9: "section";
  svg: "svg";
  footer: "footer";
  footerLogo: "div";
  logo2: typeof p.PlasmicImg;
  footerLink: "a";
  footerLink2: "a";
  footerLink4: "a";
  footerLink5: "a";
  copyRight: "p";
  socialIcons: "div";
  twitter: typeof p.PlasmicImg;
  facebook: typeof p.PlasmicImg;
  youtube: typeof p.PlasmicImg;
  vimeo: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    logoWrap: makeNodeComponent("logoWrap"),
    logo: makeNodeComponent("logo"),
    navmenu: makeNodeComponent("navmenu"),
    link3: makeNodeComponent("link3"),
    link2: makeNodeComponent("link2"),
    navBarButtonBlock: makeNodeComponent("navBarButtonBlock"),
    btnText: makeNodeComponent("btnText"),
    section1: makeNodeComponent("section1"),
    container: makeNodeComponent("container"),
    flexBox: makeNodeComponent("flexBox"),
    bannerImage: makeNodeComponent("bannerImage"),
    contentBlock: makeNodeComponent("contentBlock"),
    mainHeading: makeNodeComponent("mainHeading"),
    peraBanner: makeNodeComponent("peraBanner"),
    section2: makeNodeComponent("section2"),
    subHeading: makeNodeComponent("subHeading"),
    logoContainer: makeNodeComponent("logoContainer"),
    section3: makeNodeComponent("section3"),
    twoSideBox: makeNodeComponent("twoSideBox"),
    subHeading2: makeNodeComponent("subHeading2"),
    peraContent: makeNodeComponent("peraContent"),
    unorderList: makeNodeComponent("unorderList"),
    listIteam: makeNodeComponent("listIteam"),
    listIteam3: makeNodeComponent("listIteam3"),
    listIteam4: makeNodeComponent("listIteam4"),
    listIteam5: makeNodeComponent("listIteam5"),
    listIteam6: makeNodeComponent("listIteam6"),
    listIteam7: makeNodeComponent("listIteam7"),
    listIteam8: makeNodeComponent("listIteam8"),
    bannerImage2: makeNodeComponent("bannerImage2"),
    imageMarketing2: makeNodeComponent("imageMarketing2"),
    section4: makeNodeComponent("section4"),
    testimonialText: makeNodeComponent("testimonialText"),
    position: makeNodeComponent("position"),
    section5: makeNodeComponent("section5"),
    twoSidedContent: makeNodeComponent("twoSidedContent"),
    subHeading3: makeNodeComponent("subHeading3"),
    line2: makeNodeComponent("line2"),
    section6: makeNodeComponent("section6"),
    twoSideBox2: makeNodeComponent("twoSideBox2"),
    subHeading4: makeNodeComponent("subHeading4"),
    peraContent2: makeNodeComponent("peraContent2"),
    unorderList2: makeNodeComponent("unorderList2"),
    listIteam2: makeNodeComponent("listIteam2"),
    listIteam9: makeNodeComponent("listIteam9"),
    listIteam10: makeNodeComponent("listIteam10"),
    listIteam11: makeNodeComponent("listIteam11"),
    listIteam12: makeNodeComponent("listIteam12"),
    listIteam13: makeNodeComponent("listIteam13"),
    bannerImage3: makeNodeComponent("bannerImage3"),
    imageMarketing3: makeNodeComponent("imageMarketing3"),
    section7: makeNodeComponent("section7"),
    subHeading5: makeNodeComponent("subHeading5"),
    line3: makeNodeComponent("line3"),
    blockChapterContent: makeNodeComponent("blockChapterContent"),
    blockChapterContent4: makeNodeComponent("blockChapterContent4"),
    blockChapterContent2: makeNodeComponent("blockChapterContent2"),
    blockChapterContent3: makeNodeComponent("blockChapterContent3"),
    section8: makeNodeComponent("section8"),
    avtarContent: makeNodeComponent("avtarContent"),
    avatarImage: makeNodeComponent("avatarImage"),
    section9: makeNodeComponent("section9"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),
    footerLogo: makeNodeComponent("footerLogo"),
    logo2: makeNodeComponent("logo2"),
    footerLink: makeNodeComponent("footerLink"),
    footerLink2: makeNodeComponent("footerLink2"),
    footerLink4: makeNodeComponent("footerLink4"),
    footerLink5: makeNodeComponent("footerLink5"),
    copyRight: makeNodeComponent("copyRight"),
    socialIcons: makeNodeComponent("socialIcons"),
    twitter: makeNodeComponent("twitter"),
    facebook: makeNodeComponent("facebook"),
    youtube: makeNodeComponent("youtube"),
    vimeo: makeNodeComponent("vimeo"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
